POST http://localhost:8080/create
Content-Type: application/json


{
    "machine_id": "comfyui-online-serverless",
    "name": "comfyui-online-serverless",
    "snapshot": {
      "comfyui": "online",
      "git_custom_nodes": {},
      "file_custom_nodes": []
    },
    "callback_url": "http://127.0.0.1:3000/callback",
    "models": [],
}
